name: Auto approve

on:
  pull_request:
    branches: [master]
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      if: github.actor == 'opensentry-ci'
      with:
        github-token: "${{ secrets.CI_TOKEN }}"
