name: Automatic Merge

on:
  pull_request_review:
    types: [submitted]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@2c8e667a3386187418587517e5bfe33470d19b5b"
        env:
          GITHUB_TOKEN: "${{ secrets.CI_TOKEN }}"
          MERGE_LABELS: "automerge"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
