name: Changelog

on:
  pull_request:
    types: [closed]

  release:
    types: [published]

  issues:
    types: [closed, edited]

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: Generate changelog for master branch
    steps:
      - uses: actions/checkout@v1

      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.CI_TOKEN }}

      - name: Commit files
        env:
          CI_USER: ${{ secrets.CI_USER }}
          CI_EMAIL: ${{ secrets.CI_EMAIL }}
        run: |
          git config --local user.email "$CI_EMAIL"
          git config --local user.name "$CI_USER"
          git checkout -b changelog
          git add CHANGELOG.md && git commit -m 'Updated CHANGELOG.md' && echo ::set-env name=push::1 || echo "No changes to CHANGELOG.md"

      - name: Push changes
        if: env.push == 1
        env:
          CI_USER: ${{ secrets.CI_USER }}
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
        run: |
          git checkout -b changelog
          git push "https://$CI_USER:$CI_TOKEN@github.com/$GITHUB_REPOSITORY.git" -u origin changelog

      - name: pull-request
        if: env.push == 1
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "changelog"            # If blank, default: triggered branch
          destination_branch: "master"          # If blank, default: master
          pr_title: "Pulling ${{ github.ref }} into master"
          pr_body: "Updates to the CHANGELOG"   # Full markdown support, requires pr_title to be set
          pr_reviewer: "github[bot]"            # Comma-separated list (no spaces)
          pr_label: "automerge"                 # Comma-separated list (no spaces)
          github_token: ${{ secrets.CI_TOKEN }}
