name: Changelog

on:
  pull_request:
    types: [closed]

  release:
    types: [published]

  issues:
    types: [closed, edited]

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: Generate changelog for master branch
    steps:
      - uses: actions/checkout@v2

      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.CI_TOKEN }}
          exclude_labels: ci

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.CI_TOKEN }}
          commit-message: Updated CHANGELOG.md
          committer: ${{ secrets.CI_USER }} <${{ secrets.CI_EMAIL }}>
          author: ${{ secrets.CI_USER }} <${{ secrets.CI_EMAIL }}>
          title: 'Update CHANGELOG'
          body: |
            Update CHANGELOG.md
          labels: automerge,ci
          assignees: ${{ secrets.CI_USER }}
          branch: changelog
