name: Changelog

on:
  pull_request:
    types: [closed]
  
  release:
    types: [published]

  issues:
    types: [closed, edited]

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: Generate changelog for master branch
    steps:
      - uses: actions/checkout@v1
      
      - name: Generate changelog
        uses: charmixer/auto-changelog-action@master
        with:
          owner: 'opensentry'
          repository: 'idp'
          branch: 'master'
      
      - name: Commit files
        run: |
          git config --local user.email "team@opensentry.net"
          git config --local user.name "opensentry-ci"
          git add CHANGELOG.md && git commit -m 'Updated CHANGELOG.md' && echo ::set-env name=push::1 || echo "No changes to CHANGELOG.md"
      
      - name: Push changes
        if: env.push == 1
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_REPO_TOKEN }}
